import { useQuery } from '@tanstack/react-query'
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { NavLink } from 'react-router-dom'
import { api } from '../../lib/api'

type Summary = { total: number; statuses: Record<string, number>; vehicles_available: number; vehicles_in_use: number }
type Usage = { by_category: { category: string; total: number }[]; top_vehicles: { license_plate: string; vehicle_type: string; total: number }[] }
export function DashboardPage() {
  const summary = useQuery({ queryKey: ['dashboard-summary'], queryFn: async () => (await api.get<{ data: Summary }>('/dashboard/summary')).data.data })
  const trend = useQuery({ queryKey: ['dashboard-trend'], queryFn: async () => (await api.get<{ data: { month: string; total: number }[] }>('/dashboard/booking-trend')).data.data })
  const usage = useQuery({ queryKey: ['dashboard-usage'], queryFn: async () => (await api.get<{ data: Usage }>('/dashboard/vehicle-usage')).data.data })
  const data = summary.data
  return <><header className="page-header"><div><p className="kicker">OPERATIONS OVERVIEW</p><h1>Operational control.</h1><p>Ringkasan penggunaan armada dan keputusan booking terkini.</p></div><NavLink className="primary-link" to="/bookings">+ Booking baru</NavLink></header><section className="metric-grid"><article><span>Total booking</span><strong>{data?.total ?? '—'}</strong><small>Periode bulan berjalan</small></article><article><span>Menunggu approval</span><strong>{data ? (data.statuses.PENDING_LEVEL_1 ?? 0) + (data.statuses.PENDING_LEVEL_2 ?? 0) : '—'}</strong><small>Butuh tindakan approver</small></article><article><span>Armada tersedia</span><strong>{data?.vehicles_available ?? '—'}</strong><small>{data?.vehicles_in_use ?? 0} sedang digunakan</small></article></section><section className="overview-grid"><article className="activity-card"><div><p className="kicker">BOOKING VOLUME</p><h2>Trend booking 6 bulan</h2></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={190}><BarChart data={trend.data ?? []}><XAxis dataKey="month" fontSize={10} /><YAxis fontSize={10} allowDecimals={false} /><Tooltip /><Bar dataKey="total" fill="#2563eb" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div></article><article className="fleet-card"><p className="kicker">FLEET USAGE</p><h2>Penggunaan per kategori</h2><ResponsiveContainer width="100%" height={150}><PieChart><Pie data={usage.data?.by_category ?? []} dataKey="total" nameKey="category" innerRadius={34} outerRadius={58}>{(usage.data?.by_category ?? []).map((item, index) => <Cell key={item.category} fill={index === 0 ? '#2563eb' : '#93c5fd'} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><h3>Top 5 kendaraan</h3><ol className="top-vehicles">{usage.data?.top_vehicles.map((vehicle) => <li key={vehicle.license_plate}><span>{vehicle.license_plate} · {vehicle.vehicle_type}</span><b>{vehicle.total}x</b></li>) || <li>Belum ada pemakaian</li>}</ol></article></section></>
}
