import { useQuery } from '@tanstack/react-query'
import { useMemo, useState } from 'react'
import { Bar, BarChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { NavLink } from 'react-router-dom'
import { api } from '../../lib/api'

type Summary = { total: number; statuses: Record<string, number>; vehicles_available: number; vehicles_in_use: number; fleet: { fuel_cost: number; services_due: number }; attention: Attention[] }
type Attention = { id: number; booking_number: string; destination: string; start_at: string; status: string; license_plate: string }
type Usage = { by_category: { category: string; total: number }[]; top_vehicles: { license_plate: string; vehicle_type: string; total: number }[] }
type Lookup = { id: number; name: string; vehicle_type?: string }

export function DashboardPage() {
  const [filters, setFilters] = useState({ from: '', to: '', region_id: '', vehicle_type: '' })
  const params = useMemo(() => Object.fromEntries(Object.entries(filters).filter(([, value]) => value)), [filters])
  const summary = useQuery({ queryKey: ['dashboard-summary', params], queryFn: async () => (await api.get<{ data: Summary }>('/dashboard/summary', { params })).data.data })
  const trend = useQuery({ queryKey: ['dashboard-trend', params], queryFn: async () => (await api.get<{ data: { month: string; total: number }[] }>('/dashboard/booking-trend', { params })).data.data })
  const usage = useQuery({ queryKey: ['dashboard-usage', params], queryFn: async () => (await api.get<{ data: Usage }>('/dashboard/vehicle-usage', { params })).data.data })
  const lookups = useQuery({ queryKey: ['dashboard-lookups'], queryFn: async () => { const [regions, vehicles] = await Promise.all([api.get<{ data: Lookup[] }>('/regions'), api.get<{ data: Lookup[] }>('/vehicles')]); return { regions: regions.data.data, types: [...new Set(vehicles.data.data.map((item) => item.vehicle_type).filter(Boolean))] } } })
  const change = (key: keyof typeof filters, value: string) => setFilters((current) => ({ ...current, [key]: value }))
  const data = summary.data
  const statusCards = [{ label: 'Approved', value: data?.statuses.APPROVED ?? '—', note: 'Siap digunakan' }, { label: 'Rejected', value: data?.statuses.REJECTED ?? '—', note: 'Perlu revisi' }, { label: 'Completed', value: data?.statuses.COMPLETED ?? '—', note: 'Pemakaian selesai' }, { label: 'Biaya BBM', value: data ? `Rp ${data.fleet.fuel_cost.toLocaleString('id-ID')}` : '—', note: 'Periode terpilih' }, { label: 'Service terjadwal', value: data?.fleet.services_due ?? '—', note: '14 hari ke depan' }]
  return <><header className="page-header"><div><p className="kicker">OPERATIONS OVERVIEW</p><h1>Operational control.</h1><p>Ringkasan penggunaan armada dan keputusan booking terkini.</p></div><NavLink className="primary-link" to="/bookings">+ Booking baru</NavLink></header><section className="booking-form"><div className="form-grid"><label>Dari tanggal<input type="date" value={filters.from} onChange={(event) => change('from', event.target.value)} /></label><label>Sampai tanggal<input type="date" value={filters.to} onChange={(event) => change('to', event.target.value)} /></label><label>Region<select value={filters.region_id} onChange={(event) => change('region_id', event.target.value)}><option value="">Semua region</option>{lookups.data?.regions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Jenis kendaraan<select value={filters.vehicle_type} onChange={(event) => change('vehicle_type', event.target.value)}><option value="">Semua jenis</option>{lookups.data?.types.map((item) => <option key={item} value={item}>{item}</option>)}</select></label></div></section><section className="metric-grid"><Metric label="Total booking" value={data?.total ?? '—'} note="Periode terpilih" /><Metric label="Menunggu approval" value={data ? (data.statuses.PENDING_LEVEL_1 ?? 0) + (data.statuses.PENDING_LEVEL_2 ?? 0) : '—'} note="Butuh tindakan approver" /><Metric label="Armada tersedia" value={data?.vehicles_available ?? '—'} note={`${data?.vehicles_in_use ?? 0} sedang digunakan`} /></section><section className="metric-grid status-summary">{statusCards.map((card) => <Metric key={card.label} label={card.label} value={card.value} note={card.note} />)}</section><section className="overview-grid"><article className="activity-card"><div><p className="kicker">BOOKING VOLUME</p><h2>Trend booking</h2></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={190}><BarChart data={trend.data ?? []}><XAxis dataKey="month" fontSize={10} /><YAxis fontSize={10} allowDecimals={false} /><Tooltip /><Bar dataKey="total" fill="#2563eb" radius={[3, 3, 0, 0]} /></BarChart></ResponsiveContainer></div></article><article className="fleet-card"><p className="kicker">FLEET USAGE</p><h2>Penggunaan per kategori</h2><ResponsiveContainer width="100%" height={150}><PieChart><Pie data={usage.data?.by_category ?? []} dataKey="total" nameKey="category" innerRadius={34} outerRadius={58}>{(usage.data?.by_category ?? []).map((item, index) => <Cell key={item.category} fill={index === 0 ? '#2563eb' : '#93c5fd'} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><h3>Top 5 kendaraan</h3><ol className="top-vehicles">{usage.data?.top_vehicles.map((vehicle) => <li key={vehicle.license_plate}><span>{vehicle.license_plate} · {vehicle.vehicle_type}</span><b>{vehicle.total}x</b></li>) || <li>Belum ada pemakaian</li>}</ol></article></section><AttentionTable rows={data?.attention ?? []} /></>
}

function Metric({ label, value, note }: { label: string; value: string | number; note: string }) { return <article><span>{label}</span><strong>{value}</strong><small>{note}</small></article> }
function AttentionTable({ rows }: { rows: Attention[] }) { return <section className="table-card"><h2>Perlu perhatian</h2><table><thead><tr><th>Booking</th><th>Armada</th><th>Tujuan</th><th>Mulai</th><th>Status</th></tr></thead><tbody>{rows.length ? rows.map((booking) => <tr key={booking.id}><td>{booking.booking_number}</td><td>{booking.license_plate}</td><td>{booking.destination}</td><td>{new Date(booking.start_at).toLocaleString('id-ID')}</td><td><span className="badge">{booking.status.replaceAll('_', ' ')}</span></td></tr>) : <tr><td colSpan={5}>Tidak ada booking yang membutuhkan perhatian.</td></tr>}</tbody></table></section> }
