import { type FormEvent, type ReactNode, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../../lib/api'

type Vehicle = { id: number; license_plate: string; vehicle_type: string }
type Fuel = { id: number; license_plate: string; logged_at: string; odometer_km: number; liters: string; total_cost: string; station_name?: string }
type Service = { id: number; license_plate: string; scheduled_at: string; service_type: string; vendor_name?: string; cost: string; status: string }
type Usage = { id: number; booking_number: string; license_plate: string; driver_name: string; destination: string; started_at: string; ended_at?: string }
const initialFuel = { vehicle_id: '', logged_at: '', odometer_km: '', liters: '', price_per_liter: '', station_name: '', notes: '' }
const initialService = { vehicle_id: '', scheduled_at: '', service_type: '', odometer_km: '', vendor_name: '', cost: '', notes: '' }

export function FleetMonitoringPage() {
  const client = useQueryClient(); const [tab, setTab] = useState<'usage' | 'fuel' | 'service'>('usage'); const [fuel, setFuel] = useState(initialFuel); const [service, setService] = useState(initialService); const [error, setError] = useState('')
  const vehicles = useQuery({ queryKey: ['fleet-vehicles'], queryFn: async () => (await api.get<{ data: Vehicle[] }>('/vehicles')).data.data })
  const fuelLogs = useQuery({ queryKey: ['fuel-logs'], queryFn: async () => (await api.get<{ data: Fuel[] }>('/fleet/fuel-logs')).data.data })
  const services = useQuery({ queryKey: ['vehicle-services'], queryFn: async () => (await api.get<{ data: Service[] }>('/fleet/services')).data.data })
  const usage = useQuery({ queryKey: ['fleet-usage'], queryFn: async () => (await api.get<{ data: Usage[] }>('/fleet/usage')).data.data })
  const setFuelField = (key: keyof typeof initialFuel, value: string) => setFuel((current) => ({ ...current, [key]: value })); const setServiceField = (key: keyof typeof initialService, value: string) => setService((current) => ({ ...current, [key]: value }))
  async function submitFuel(event: FormEvent) { event.preventDefault(); setError(''); try { await api.post('/fleet/fuel-logs', { ...fuel, vehicle_id: +fuel.vehicle_id, odometer_km: +fuel.odometer_km, liters: +fuel.liters, price_per_liter: +fuel.price_per_liter }); setFuel(initialFuel); client.invalidateQueries({ queryKey: ['fuel-logs'] }) } catch (e: any) { setError(e.response?.data?.message ?? 'Log BBM gagal disimpan.') } }
  async function submitService(event: FormEvent) { event.preventDefault(); setError(''); try { await api.post('/fleet/services', { ...service, vehicle_id: +service.vehicle_id, odometer_km: service.odometer_km ? +service.odometer_km : undefined, cost: service.cost ? +service.cost : undefined }); setService(initialService); client.invalidateQueries({ queryKey: ['vehicle-services'] }) } catch (e: any) { setError(e.response?.data?.message ?? 'Jadwal service gagal disimpan.') } }
  async function complete(id: number) { try { await api.post(`/fleet/services/${id}/complete`); client.invalidateQueries({ queryKey: ['vehicle-services'] }) } catch (e: any) { setError(e.response?.data?.message ?? 'Service gagal diselesaikan.') } }
  return <section className="booking-page"><header><div><p className="kicker">FLEET MONITORING</p><h1>Kesehatan armada.</h1><p>Pantau pemakaian, konsumsi BBM, dan jadwal service kendaraan.</p></div></header><div className="table-toolbar"><button onClick={() => setTab('usage')} disabled={tab === 'usage'}>Riwayat pemakaian</button><button onClick={() => setTab('fuel')} disabled={tab === 'fuel'}>Konsumsi BBM</button><button onClick={() => setTab('service')} disabled={tab === 'service'}>Jadwal service</button></div>{error && <p className="error">{error}</p>}{tab === 'usage' && <UsageTable rows={usage.data ?? []} />}{tab === 'fuel' && <><FuelForm form={fuel} set={setFuelField} vehicles={vehicles.data ?? []} submit={submitFuel} /><FuelTable rows={fuelLogs.data ?? []} /></>}{tab === 'service' && <><ServiceForm form={service} set={setServiceField} vehicles={vehicles.data ?? []} submit={submitService} /><ServiceTable rows={services.data ?? []} complete={complete} /></>}</section>
}
function VehicleSelect({ value, set, vehicles }: { value: string; set: (value: string) => void; vehicles: Vehicle[] }) { return <label>Kendaraan<select required value={value} onChange={(event) => set(event.target.value)}><option value="">Pilih kendaraan</option>{vehicles.map((vehicle) => <option key={vehicle.id} value={vehicle.id}>{vehicle.license_plate} · {vehicle.vehicle_type}</option>)}</select></label> }
function Field({ label, value, set, type = 'text', required = false }: { label: string; value: string; set: (value: string) => void; type?: string; required?: boolean }) { return <label>{label}<input required={required} type={type} value={value} onChange={(event) => set(event.target.value)} /></label> }
function FuelForm({ form, set, vehicles, submit }: { form: typeof initialFuel; set: (key: keyof typeof initialFuel, value: string) => void; vehicles: Vehicle[]; submit: (event: FormEvent) => Promise<void> }) { return <form className="booking-form" onSubmit={submit}><h2>Catat konsumsi BBM</h2><div className="form-grid"><VehicleSelect value={form.vehicle_id} set={(v) => set('vehicle_id', v)} vehicles={vehicles} /><Field label="Tanggal & waktu" type="datetime-local" value={form.logged_at} set={(v) => set('logged_at', v)} required /><Field label="Odometer (km)" type="number" value={form.odometer_km} set={(v) => set('odometer_km', v)} required /><Field label="Liter" type="number" value={form.liters} set={(v) => set('liters', v)} required /><Field label="Harga per liter" type="number" value={form.price_per_liter} set={(v) => set('price_per_liter', v)} required /><Field label="SPBU/vendor" value={form.station_name} set={(v) => set('station_name', v)} /><Field label="Catatan" value={form.notes} set={(v) => set('notes', v)} /></div><button type="submit">Simpan log BBM</button></form> }
function ServiceForm({ form, set, vehicles, submit }: { form: typeof initialService; set: (key: keyof typeof initialService, value: string) => void; vehicles: Vehicle[]; submit: (event: FormEvent) => Promise<void> }) { return <form className="booking-form" onSubmit={submit}><h2>Jadwalkan service</h2><div className="form-grid"><VehicleSelect value={form.vehicle_id} set={(v) => set('vehicle_id', v)} vehicles={vehicles} /><Field label="Tanggal service" type="date" value={form.scheduled_at} set={(v) => set('scheduled_at', v)} required /><Field label="Jenis service" value={form.service_type} set={(v) => set('service_type', v)} required /><Field label="Odometer (km)" type="number" value={form.odometer_km} set={(v) => set('odometer_km', v)} /><Field label="Bengkel/vendor" value={form.vendor_name} set={(v) => set('vendor_name', v)} /><Field label="Estimasi biaya" type="number" value={form.cost} set={(v) => set('cost', v)} /><Field label="Catatan" value={form.notes} set={(v) => set('notes', v)} /></div><button type="submit">Simpan jadwal service</button></form> }
function UsageTable({ rows }: { rows: Usage[] }) { return <Table headers={['Booking', 'Kendaraan', 'Driver', 'Tujuan', 'Mulai', 'Selesai']}>{rows.length ? rows.map((row) => <tr key={row.id}><td>{row.booking_number}</td><td>{row.license_plate}</td><td>{row.driver_name}</td><td>{row.destination}</td><td>{row.started_at}</td><td>{row.ended_at ?? 'Berjalan'}</td></tr>) : <Empty cols={6} text="Belum ada riwayat pemakaian." />}</Table> }
function FuelTable({ rows }: { rows: Fuel[] }) { return <Table headers={['Kendaraan', 'Tanggal', 'Odometer', 'Liter', 'Biaya', 'SPBU/vendor']}>{rows.length ? rows.map((row) => <tr key={row.id}><td>{row.license_plate}</td><td>{row.logged_at}</td><td>{row.odometer_km.toLocaleString('id-ID')} km</td><td>{row.liters} L</td><td>Rp {Number(row.total_cost).toLocaleString('id-ID')}</td><td>{row.station_name || '—'}</td></tr>) : <Empty cols={6} text="Belum ada log BBM." />}</Table> }
function ServiceTable({ rows, complete }: { rows: Service[]; complete: (id: number) => Promise<void> }) { return <Table headers={['Kendaraan', 'Jenis', 'Jadwal', 'Vendor', 'Biaya', 'Status']}>{rows.length ? rows.map((row) => <tr key={row.id}><td>{row.license_plate}</td><td>{row.service_type}</td><td>{row.scheduled_at}</td><td>{row.vendor_name || '—'}</td><td>Rp {Number(row.cost).toLocaleString('id-ID')}</td><td><span className="badge">{row.status}</span>{row.status === 'SCHEDULED' && <button onClick={() => complete(row.id)}>Selesaikan</button>}</td></tr>) : <Empty cols={6} text="Belum ada jadwal service." />}</Table> }
function Table({ headers, children }: { headers: string[]; children: ReactNode }) { return <section className="table-card"><table><thead><tr>{headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{children}</tbody></table></section> }
function Empty({ cols, text }: { cols: number; text: string }) { return <tr><td colSpan={cols}>{text}</td></tr> }
