import { type FormEvent, type ReactNode, useState } from 'react'
import { NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { useAuth } from './features/auth/AuthContext'
import { BookingPage } from './features/bookings/BookingPage'
import './App.css'

function LoginPage() {
  const { user, login } = useAuth(); const navigate = useNavigate()
  const [email, setEmail] = useState('admin@vehicle.test'); const [password, setPassword] = useState('Password123!'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  if (user) return <Navigate to="/dashboard" replace />
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { await login(email, password); navigate('/dashboard') } catch (error) { setError(error instanceof Error ? error.message : 'Email atau password tidak valid.') } finally { setLoading(false) } }
  return <main className="auth-page"><section className="auth-panel"><div className="brand"><span className="brand-mark">V</span><span>VEHICLE OPS</span></div><p className="kicker">OPERATIONS CONTROL</p><h1>Every trip,<br />under control.</h1><p>Kelola armada, jadwal, dan approval dengan satu alur operasional yang jelas.</p><div className="auth-proof"><span>01</span><span>02</span><span>03</span><b>Booking</b><b>Approval</b><b>Complete</b></div></section><section className="auth-form-wrap"><form className="auth-form" onSubmit={submit}><p className="kicker">SECURE ACCESS</p><h2>Masuk ke workspace</h2><p className="form-copy">Gunakan akun operasional untuk melanjutkan.</p><label>Email<input value={email} onChange={(e) => setEmail(e.target.value)} type="email" required /></label><label>Password<input value={password} onChange={(e) => setPassword(e.target.value)} type="password" required /></label>{error && <p className="error">{error}</p>}<button disabled={loading}>{loading ? 'Memverifikasi...' : 'Masuk'}</button><p className="demo-note">Demo account: admin@vehicle.test</p></form></section></main>
}

export function AppShell({ children }: { children: ReactNode }) {
  const { user, logout } = useAuth(); const navigate = useNavigate(); if (!user) return <Navigate to="/login" replace />
  return <main className="workspace"><aside className="sidebar"><div className="brand"><span className="brand-mark">V</span><span>VEHICLE OPS</span></div><div className="user-card"><span className="avatar">{user.name.slice(0, 1)}</span><div><b>{user.name}</b><small>{user.role === 'admin' ? 'Admin Pool' : 'Approver'}</small></div></div><nav><p>WORKSPACE</p><NavLink to="/dashboard">Overview</NavLink><NavLink to="/bookings">Booking</NavLink><a className="disabled">Kendaraan</a><a className="disabled">Driver</a><p className="nav-space">INSIGHTS</p><a className="disabled">Laporan</a><a className="disabled">Activity log</a></nav><button className="signout" onClick={() => { logout(); navigate('/login') }}>Keluar workspace</button></aside><section className="main-content">{children}</section></main>
}

function Dashboard() { return <AppShell><header className="page-header"><div><p className="kicker">OPERATIONS OVERVIEW</p><h1>Good morning, Admin.</h1><p>Berikut ringkasan kondisi armada hari ini.</p></div><NavLink className="primary-link" to="/bookings">+ Booking baru</NavLink></header><section className="metric-grid"><article><span>Booking aktif</span><strong>0</strong><small>Belum ada perjalanan hari ini</small></article><article><span>Menunggu approval</span><strong>0</strong><small>Alur approval masih kosong</small></article><article><span>Armada tersedia</span><strong>02</strong><small>Dari 2 armada operasional</small></article></section><section className="overview-grid"><article className="activity-card"><div><p className="kicker">UP NEXT</p><h2>Aktivitas terdekat</h2></div><div className="empty-state"><span>↗</span><p>Belum ada booking yang dijadwalkan.</p><NavLink to="/bookings">Buat booking pertama</NavLink></div></article><article className="fleet-card"><p className="kicker">FLEET PULSE</p><h2>Armada siap pakai</h2><div className="fleet-number">2 <span>/ 2 available</span></div><div className="progress"><i /></div><small>Semua kendaraan demo berstatus tersedia.</small></article></section></AppShell> }

export default function App() { return <Routes><Route path="/login" element={<LoginPage />} /><Route path="/dashboard" element={<Dashboard />} /><Route path="/bookings" element={<AppShell><BookingPage /></AppShell>} /><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes> }
