import { type FormEvent, useMemo, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { api } from '../../lib/api'
import './MasterDataPage.css'

type Resource = 'regions' | 'vehicles' | 'drivers' | 'users'
type Field = { key: string; label: string; type?: string; options?: string[] }
const schema: Record<Resource, { title: string; fields: Field[]; columns: string[] }> = {
  regions: { title: 'Region', fields: [{ key: 'code', label: 'Kode' }, { key: 'name', label: 'Nama region' }], columns: ['code', 'name', 'is_active'] },
  vehicles: { title: 'Kendaraan', fields: [{ key: 'region_id', label: 'Region' }, { key: 'vehicle_code', label: 'Kode kendaraan' }, { key: 'license_plate', label: 'Nomor polisi' }, { key: 'vehicle_type', label: 'Tipe kendaraan' }, { key: 'category', label: 'Kategori', type: 'select', options: ['PASSENGER', 'CARGO'] }, { key: 'ownership_status', label: 'Kepemilikan', type: 'select', options: ['COMPANY', 'RENTAL'] }, { key: 'operational_status', label: 'Status', type: 'select', options: ['AVAILABLE', 'MAINTENANCE', 'INACTIVE'] }], columns: ['vehicle_code', 'license_plate', 'vehicle_type', 'category', 'operational_status'] },
  drivers: { title: 'Driver', fields: [{ key: 'region_id', label: 'Region' }, { key: 'name', label: 'Nama' }, { key: 'phone_number', label: 'Telepon' }, { key: 'license_number', label: 'Nomor SIM' }, { key: 'license_expires_at', label: 'Masa berlaku SIM', type: 'date' }], columns: ['name', 'phone_number', 'license_number', 'license_expires_at', 'is_active'] },
  users: { title: 'User & Approver', fields: [{ key: 'name', label: 'Nama' }, { key: 'email', label: 'Email' }, { key: 'role', label: 'Role', type: 'select', options: ['admin', 'approver'] }, { key: 'approval_level', label: 'Approval level', type: 'select', options: ['1', '2'] }, { key: 'password', label: 'Password' }], columns: ['name', 'email', 'role', 'approval_level', 'is_active'] },
}

export function MasterDataPage({ resource }: { resource: Resource }) {
  const config = schema[resource]; const client = useQueryClient(); const [editing, setEditing] = useState<Record<string, string> | null>(null); const [error, setError] = useState('')
  const list = useQuery({ queryKey: ['admin', resource], queryFn: async () => (await api.get<{ data: Record<string, unknown>[] }>(`/admin/${resource}`)).data.data })
  const regions = useQuery({ queryKey: ['admin', 'regions'], queryFn: async () => (await api.get<{ data: Record<string, unknown>[] }>('/admin/regions')).data.data, enabled: ['vehicles', 'drivers'].includes(resource) })
  const initial = useMemo(() => Object.fromEntries(config.fields.map((field) => [field.key, ''])), [config.fields]); const values = editing ?? initial
  async function save(event: FormEvent) { event.preventDefault(); setError(''); const payload = { ...values, ...(resource === 'users' ? {} : { is_active: '1' }) }; try { if (editing?.id) await api.put(`/admin/${resource}/${editing.id}`, payload); else await api.post(`/admin/${resource}`, payload); setEditing(null); client.invalidateQueries({ queryKey: ['admin', resource] }) } catch (e: any) { setError(e.response?.data?.message ?? 'Data tidak dapat disimpan.') } }
  async function remove(id: unknown) { if (!confirm('Hapus data ini?')) return; try { await api.delete(`/admin/${resource}/${id}`); client.invalidateQueries({ queryKey: ['admin', resource] }) } catch (e: any) { setError(e.response?.data?.message ?? 'Data tidak dapat dihapus.') } }
  return <section className="booking-page"><header><div><p className="kicker">MASTER DATA</p><h1>{config.title}.</h1><p>Kelola data yang dipakai dalam workflow booking.</p></div><button onClick={() => setEditing({ ...initial })}>+ Tambah data</button></header>{editing && <form className="booking-form" onSubmit={save}><h2>{editing.id ? 'Ubah data' : `Tambah ${config.title.toLowerCase()}`}</h2><div className="form-grid">{config.fields.map((field) => <label key={field.key}>{field.label}{field.key === 'region_id' ? <select required value={values[field.key] ?? ''} onChange={(e) => setEditing({ ...values, [field.key]: e.target.value })}><option value="">Pilih region</option>{regions.data?.map((region) => <option value={String(region.id)} key={String(region.id)}>{String(region.name)}</option>)}</select> : field.type === 'select' ? <select value={values[field.key] ?? ''} onChange={(e) => setEditing({ ...values, [field.key]: e.target.value })}><option value="">Pilih</option>{field.options?.map((option) => <option key={option}>{option}</option>)}</select> : <input required={field.key !== 'approval_level'} type={field.type ?? (field.key === 'password' ? 'password' : 'text')} value={values[field.key] ?? ''} onChange={(e) => setEditing({ ...values, [field.key]: e.target.value })} />}</label>)}</div>{error && <p className="error">{error}</p>}<div><button type="button" className="ghost" onClick={() => setEditing(null)}>Batal</button><button type="submit">Simpan</button></div></form>}<section className="table-card"><table><thead><tr>{config.columns.map((column) => <th key={column}>{column.replaceAll('_', ' ')}</th>)}<th>Aksi</th></tr></thead><tbody>{list.isLoading ? <tr><td colSpan={config.columns.length + 1}>Memuat data...</td></tr> : list.data?.map((row) => <tr key={String(row.id)}>{config.columns.map((column) => <td key={column}>{String(row[column] ?? '—')}</td>)}<td><button className="table-action" onClick={() => setEditing(Object.fromEntries(Object.entries(row).map(([key, value]) => [key, String(value ?? '')]))) }>Edit</button><button className="table-action danger-text" onClick={() => remove(row.id)}>Hapus</button></td></tr>)}</tbody></table></section></section>
}
