import { type FormEvent, useEffect, useMemo, useRef, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Navigate, useLocation, useNavigate } from 'react-router-dom'
import { api } from '../../lib/api'
import { useAuth } from '../auth/AuthContext'

type Lookup = { id: number; name?: string; license_plate?: string; vehicle_type?: string; category?: string; approval_level?: number }
type Booking = { id: number; booking_number: string; requester_name: string; requester_nik: string; department: string; region_id: number; vehicle_id: number; driver_id: number; purpose: string; destination: string; start_at: string; end_at: string; passenger_count: number; requested_vehicle_category: 'PASSENGER' | 'CARGO'; approver_level_1_id: number; approver_level_2_id: number; notes?: string; status: string; license_plate: string; driver_name: string }
type Approval = { id: number; approval_level: number; status: string; approver_name: string; remarks?: string }
type PageResult = { data: Booking[]; meta: { page: number; per_page: number; total: number } }
const initial = { requester_name: '', requester_nik: '', department: '', region_id: '', vehicle_id: '', driver_id: '', purpose: '', destination: '', start_at: '', end_at: '', passenger_count: '1', requested_vehicle_category: 'PASSENGER', approver_level_1_id: '', approver_level_2_id: '', notes: '' }

export function BookingPage() {
  const { user } = useAuth(); const client = useQueryClient()
  const location = useLocation(); const navigate = useNavigate()
  const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(initial); const [editingId, setEditingId] = useState<number | null>(null); const [selected, setSelected] = useState<number | null>(null); const [error, setError] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1)
  useEffect(() => { if ((location.state as { openForm?: boolean } | null)?.openForm) { setShowForm(true); navigate(location.pathname, { replace: true, state: null }) } }, [location, navigate])
  const params = useMemo(() => ({ search, status, page, per_page: 10 }), [search, status, page])
  const bookings = useQuery({ queryKey: ['bookings', params], queryFn: async () => (await api.get<PageResult>('/bookings', { params })).data })
  const details = useQuery({ queryKey: ['booking-detail', selected], enabled: selected !== null, queryFn: async () => (await api.get<{ data: Booking }>(`/bookings/${selected}`)).data.data })
  const history = useQuery({ queryKey: ['booking-history', selected], enabled: selected !== null, queryFn: async () => (await api.get<{ data: Approval[] }>(`/bookings/${selected}/approval-history`)).data.data })
  const lookups = useQuery({ queryKey: ['booking-lookups'], queryFn: async () => { const responses = await Promise.all(['regions', 'vehicles', 'drivers', 'approvers'].map((path) => api.get<{ data: Lookup[] }>(`/${path}`))); return { regions: responses[0].data.data, vehicles: responses[1].data.data, drivers: responses[2].data.data, approvers: responses[3].data.data } } })
  if (!user) return <Navigate to="/login" replace />
  const set = (key: keyof typeof initial, value: string) => setForm((current) => ({ ...current, [key]: value }))
  const payload = () => ({ ...form, region_id: +form.region_id, vehicle_id: +form.vehicle_id, driver_id: +form.driver_id, passenger_count: +form.passenger_count, approver_level_1_id: +form.approver_level_1_id, approver_level_2_id: +form.approver_level_2_id })
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); try { if (editingId) await api.put(`/bookings/${editingId}`, payload()); else await api.post('/bookings', payload()); setForm(initial); setEditingId(null); setShowForm(false); client.invalidateQueries({ queryKey: ['bookings'] }); client.invalidateQueries({ queryKey: ['booking-detail'] }); client.invalidateQueries({ queryKey: ['booking-history'] }) } catch (e: any) { setError(e.response?.data?.message ?? 'Booking gagal disimpan.') } }
  function edit(booking: Booking) { setForm({ requester_name: booking.requester_name, requester_nik: booking.requester_nik, department: booking.department, region_id: String(booking.region_id), vehicle_id: String(booking.vehicle_id), driver_id: String(booking.driver_id), purpose: booking.purpose, destination: booking.destination, start_at: booking.start_at.slice(0, 16), end_at: booking.end_at.slice(0, 16), passenger_count: String(booking.passenger_count), requested_vehicle_category: booking.requested_vehicle_category, approver_level_1_id: String(booking.approver_level_1_id), approver_level_2_id: String(booking.approver_level_2_id), notes: booking.notes ?? '' }); setEditingId(booking.id); setError(''); setShowForm(true); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  async function cancel(booking: Booking) { if (!window.confirm(`Batalkan booking ${booking.booking_number}?`)) return; try { await api.delete(`/bookings/${booking.id}`); if (selected === booking.id) setSelected(null); client.invalidateQueries({ queryKey: ['bookings'] }) } catch (e: any) { setError(e.response?.data?.message ?? 'Booking gagal dibatalkan.') } }
  const data = lookups.data; const vehicles = (data?.vehicles ?? []).filter((vehicle) => vehicle.category === form.requested_vehicle_category); const canModify = (value: Booking) => ['DRAFT', 'PENDING_LEVEL_1', 'PENDING_LEVEL_2'].includes(value.status); const totalPages = Math.max(1, Math.ceil((bookings.data?.meta.total ?? 0) / 10))
  return <section className="booking-page"><header><div><p className="kicker">BOOKINGS</p><h1>Pemesanan kendaraan.</h1><p>Buat, revisi, dan pantau perjalanan operasional.</p></div><button onClick={() => { setShowForm(!showForm); if (showForm) { setEditingId(null); setForm(initial) } }}>{showForm ? 'Tutup form' : 'Booking baru'}</button></header>{showForm && <BookingForm form={form} set={set} data={data} vehicles={vehicles} editing={editingId !== null} error={error} submit={submit} />}{error && !showForm && <p className="error">{error}</p>}<section className="table-card"><div className="table-toolbar booking-toolbar"><input aria-label="Cari booking" placeholder="Cari nomor, pemohon, atau kendaraan" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} /><StatusFilter value={status} onChange={(value) => { setStatus(value); setPage(1) }} /></div><table><thead><tr><th>No. booking</th><th>Pemohon</th><th>Armada</th><th>Tujuan</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{bookings.isLoading ? <tr><td colSpan={6}>Memuat booking...</td></tr> : bookings.data?.data.length ? bookings.data.data.map((booking) => <tr key={booking.id}><td><button className="link-button" onClick={() => setSelected(booking.id)}>{booking.booking_number}</button></td><td>{booking.requester_name}</td><td>{booking.license_plate} · {booking.driver_name}</td><td>{booking.destination}</td><td><span className="badge">{booking.status.replaceAll('_', ' ')}</span></td><td className="table-actions"><button onClick={() => setSelected(booking.id)}>Detail</button>{canModify(booking) && <><button onClick={() => edit(booking)}>Revisi</button><button className="danger" onClick={() => cancel(booking)}>Batalkan</button></>}</td></tr>) : <tr><td colSpan={6}>Tidak ada booking yang cocok.</td></tr>}</tbody></table><div className="table-toolbar table-pagination"><span>{bookings.data?.meta.total ?? 0} hasil · halaman {page}/{totalPages}</span><div className="table-actions"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Sebelumnya</button><button disabled={page >= totalPages} onClick={() => setPage(page + 1)}>Berikutnya</button></div></div></section>{selected && <BookingDetail booking={details.data} history={history.data ?? []} close={() => setSelected(null)} />}</section>
}

const statusOptions = ['', 'PENDING_LEVEL_1', 'PENDING_LEVEL_2', 'APPROVED', 'REJECTED', 'COMPLETED']
function StatusFilter({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null)
  useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false) }; window.addEventListener('mousedown', close); return () => window.removeEventListener('mousedown', close) }, [])
  const label = value ? value.replaceAll('_', ' ') : 'Semua status'
  return <div className="status-filter" ref={root}><button type="button" className="status-trigger" aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen((current) => !current)}><span>{label}</span><i aria-hidden="true" /></button>{open && <div className="status-menu" role="listbox" aria-label="Filter status">{statusOptions.map((option) => <button key={option || 'all'} type="button" role="option" aria-selected={value === option} className={value === option ? 'selected' : ''} onClick={() => { onChange(option); setOpen(false) }}>{option ? option.replaceAll('_', ' ') : 'Semua status'}</button>)}</div>}</div>
}

function BookingForm({ form, set, data, vehicles, editing, error, submit }: { form: typeof initial; set: (key: keyof typeof initial, value: string) => void; data: { regions: Lookup[]; vehicles: Lookup[]; drivers: Lookup[]; approvers: Lookup[] } | undefined; vehicles: Lookup[]; editing: boolean; error: string; submit: (event: FormEvent) => Promise<void> }) { return <form className="booking-form" onSubmit={submit}><h2>{editing ? 'Revisi booking' : 'Informasi pemohon dan perjalanan'}</h2><p>{editing ? 'Perubahan akan mengulang approval dari Level 1.' : 'Booking baru langsung dikirim ke approval Level 1.'}</p><div className="form-grid"><Input label="Nama pemohon" value={form.requester_name} set={(v) => set('requester_name', v)} /><Input label="NIK" value={form.requester_nik} set={(v) => set('requester_nik', v)} /><Input label="Departemen" value={form.department} set={(v) => set('department', v)} /><Select label="Region" value={form.region_id} set={(v) => set('region_id', v)} options={data?.regions ?? []} /><Input label="Tujuan" value={form.destination} set={(v) => set('destination', v)} /><Input label="Keperluan" value={form.purpose} set={(v) => set('purpose', v)} /><Input label="Mulai" type="datetime-local" value={form.start_at} set={(v) => set('start_at', v)} /><Input label="Selesai" type="datetime-local" value={form.end_at} set={(v) => set('end_at', v)} /><Select label="Kategori kendaraan" value={form.requested_vehicle_category} set={(v) => set('requested_vehicle_category', v)} options={[{ id: 1, name: 'PASSENGER' }, { id: 2, name: 'CARGO' }]} /><Input label="Jumlah penumpang" type="number" value={form.passenger_count} set={(v) => set('passenger_count', v)} /><Select label="Kendaraan" value={form.vehicle_id} set={(v) => set('vehicle_id', v)} options={vehicles} vehicle /><Select label="Driver" value={form.driver_id} set={(v) => set('driver_id', v)} options={data?.drivers ?? []} /><Select label="Approver L1" value={form.approver_level_1_id} set={(v) => set('approver_level_1_id', v)} options={(data?.approvers ?? []).filter((item) => item.approval_level === 1)} /><Select label="Approver L2" value={form.approver_level_2_id} set={(v) => set('approver_level_2_id', v)} options={(data?.approvers ?? []).filter((item) => item.approval_level === 2)} /><Input label="Catatan" value={form.notes} set={(v) => set('notes', v)} /></div>{error && <p className="error">{error}</p>}<button type="submit">{editing ? 'Simpan revisi' : 'Kirim untuk approval'}</button></form> }
function BookingDetail({ booking, history, close }: { booking: Booking | undefined; history: Approval[]; close: () => void }) { return <section className="detail-card"><div><p className="kicker">DETAIL BOOKING</p><h2>{booking?.booking_number ?? 'Memuat...'}</h2></div><button onClick={close}>Tutup</button>{booking && <div className="detail-grid"><p><strong>Pemohon</strong>{booking.requester_name} · {booking.department}</p><p><strong>Perjalanan</strong>{booking.destination}<br />{booking.start_at} → {booking.end_at}</p><p><strong>Armada</strong>{booking.license_plate} · {booking.driver_name}</p><p><strong>Status</strong><span className="badge">{booking.status.replaceAll('_', ' ')}</span></p></div>}<h3>Riwayat approval</h3><ol className="approval-history">{history.map((item) => <li key={item.id}><strong>Level {item.approval_level}: {item.approver_name}</strong><span>{item.status.replaceAll('_', ' ')}{item.remarks ? ` — ${item.remarks}` : ''}</span></li>)}</ol></section> }
function Input({ label, value, set, type = 'text' }: { label: string; value: string; set: (value: string) => void; type?: string }) { return <label>{label}<input required type={type} value={value} onChange={(event) => set(event.target.value)} /></label> }
function Select({ label, value, set, options, vehicle }: { label: string; value: string; set: (value: string) => void; options: Lookup[]; vehicle?: boolean }) { return <label>{label}<select required value={value} onChange={(event) => set(event.target.value)}><option value="">Pilih {label}</option>{options.map((option) => <option key={option.id} value={option.id}>{vehicle ? `${option.license_plate} · ${option.vehicle_type}` : option.name}</option>)}</select></label> }
