import { type FormEvent, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Navigate } from 'react-router-dom'
import { api } from '../../lib/api'
import { useAuth } from '../auth/AuthContext'

type Lookup = { id: number; name?: string; license_plate?: string; vehicle_type?: string; category?: string; approval_level?: number }
type Booking = { id: number; booking_number: string; requester_name: string; destination: string; status: string; license_plate: string; driver_name: string }
const initial = { requester_name: '', requester_nik: '', department: '', region_id: '', vehicle_id: '', driver_id: '', purpose: '', destination: '', start_at: '', end_at: '', passenger_count: '1', requested_vehicle_category: 'PASSENGER', approver_level_1_id: '', approver_level_2_id: '', notes: '' }
export function BookingPage() {
  const { user } = useAuth(); const client = useQueryClient(); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState(initial); const [error, setError] = useState('')
  const bookings = useQuery({ queryKey: ['bookings'], queryFn: async () => (await api.get<{ data: Booking[] }>('/bookings')).data.data })
  const lookups = useQuery({ queryKey: ['booking-lookups'], queryFn: async () => { const responses = await Promise.all(['regions','vehicles','drivers','approvers'].map((path) => api.get<{ data: Lookup[] }>(`/${path}`))); return { regions: responses[0].data.data, vehicles: responses[1].data.data, drivers: responses[2].data.data, approvers: responses[3].data.data } } })
  if (!user) return <Navigate to="/login" replace />
  const set = (key: keyof typeof initial, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); try { await api.post('/bookings', { ...form, region_id: +form.region_id, vehicle_id: +form.vehicle_id, driver_id: +form.driver_id, passenger_count: +form.passenger_count, approver_level_1_id: +form.approver_level_1_id, approver_level_2_id: +form.approver_level_2_id }); setForm(initial); setShowForm(false); client.invalidateQueries({ queryKey: ['bookings'] }) } catch (e: any) { setError(e.response?.data?.message ?? 'Booking gagal dibuat.') } }
  const data = lookups.data; const vehicles = (data?.vehicles ?? []).filter((vehicle) => vehicle.category === form.requested_vehicle_category)
  return <section className="booking-page"><header><div><p className="kicker">BOOKINGS</p><h1>Pemesanan kendaraan.</h1><p>Buat dan pantau perjalanan operasional.</p></div><button onClick={() => setShowForm(!showForm)}>{showForm ? 'Tutup form' : '+ Booking baru'}</button></header>{showForm && <form className="booking-form" onSubmit={submit}><h2>Informasi pemohon dan perjalanan</h2><div className="form-grid"><Input label="Nama pemohon" value={form.requester_name} set={(v) => set('requester_name', v)} /><Input label="NIK" value={form.requester_nik} set={(v) => set('requester_nik', v)} /><Input label="Departemen" value={form.department} set={(v) => set('department', v)} /><Select label="Region" value={form.region_id} set={(v) => set('region_id', v)} options={data?.regions ?? []} /><Input label="Tujuan" value={form.destination} set={(v) => set('destination', v)} /><Input label="Keperluan" value={form.purpose} set={(v) => set('purpose', v)} /><Input label="Mulai" type="datetime-local" value={form.start_at} set={(v) => set('start_at', v)} /><Input label="Selesai" type="datetime-local" value={form.end_at} set={(v) => set('end_at', v)} /><Select label="Kategori kendaraan" value={form.requested_vehicle_category} set={(v) => set('requested_vehicle_category', v)} options={[{ id: 1, name: 'PASSENGER' }, { id: 2, name: 'CARGO' }]} /><Input label="Jumlah penumpang" type="number" value={form.passenger_count} set={(v) => set('passenger_count', v)} /><Select label="Kendaraan" value={form.vehicle_id} set={(v) => set('vehicle_id', v)} options={vehicles} vehicle /><Select label="Driver" value={form.driver_id} set={(v) => set('driver_id', v)} options={data?.drivers ?? []} /><Select label="Approver L1" value={form.approver_level_1_id} set={(v) => set('approver_level_1_id', v)} options={(data?.approvers ?? []).filter((item) => item.approval_level === 1)} /><Select label="Approver L2" value={form.approver_level_2_id} set={(v) => set('approver_level_2_id', v)} options={(data?.approvers ?? []).filter((item) => item.approval_level === 2)} /></div>{error && <p className="error">{error}</p>}<button type="submit">Kirim untuk approval</button></form>}<section className="table-card"><table><thead><tr><th>No. booking</th><th>Pemohon</th><th>Armada</th><th>Tujuan</th><th>Status</th></tr></thead><tbody>{bookings.data?.map((booking) => <tr key={booking.id}><td>{booking.booking_number}</td><td>{booking.requester_name}</td><td>{booking.license_plate} · {booking.driver_name}</td><td>{booking.destination}</td><td><span className="badge">{booking.status.replaceAll('_', ' ')}</span></td></tr>)}</tbody></table></section></section>
}
function Input({ label, value, set, type = 'text' }: { label: string; value: string; set: (value: string) => void; type?: string }) { return <label>{label}<input required type={type} value={value} onChange={(event) => set(event.target.value)} /></label> }
function Select({ label, value, set, options, vehicle }: { label: string; value: string; set: (value: string) => void; options: Lookup[]; vehicle?: boolean }) { return <label>{label}<select required value={value} onChange={(event) => set(event.target.value)}><option value="">Pilih {label}</option>{options.map((option) => <option key={option.id} value={option.id}>{vehicle ? `${option.license_plate} · ${option.vehicle_type}` : option.name}</option>)}</select></label> }
