import { useQuery } from '@tanstack/react-query'
import { useState } from 'react'
import { api } from '../../lib/api'

type Lookup = { id: number; name: string; license_plate?: string }
type ReportRow = { id: number; booking_number: string; requester_name: string; destination: string; license_plate: string; driver_name: string; region_name: string; start_at: string; status: string }
type ReportResponse = { data: ReportRow[]; meta: { page: number; per_page: number; total: number } }
export function ReportsPage() {
  const [filters, setFilters] = useState({ status: '', region_id: '', vehicle_id: '', vehicle_category: '', from: '', to: '', search: '' }); const [page, setPage] = useState(1)
  const params = { ...Object.fromEntries(Object.entries(filters).filter(([, value]) => value)), page, per_page: 10 }
  const report = useQuery({ queryKey: ['booking-report', params], queryFn: async () => (await api.get<ReportResponse>('/reports/bookings', { params })).data })
  const lookups = useQuery({ queryKey: ['report-lookups'], queryFn: async () => { const responses = await Promise.all(['regions', 'vehicles'].map((path) => api.get<{ data: Lookup[] }>(`/${path}`))); return { regions: responses[0].data.data, vehicles: responses[1].data.data } } })
  const change = (key: keyof typeof filters, value: string) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1) }
  async function download() { const response = await api.get('/reports/bookings/export', { params: Object.fromEntries(Object.entries(filters).filter(([, value]) => value)), responseType: 'blob' }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = 'vehicle-booking-report.xlsx'; link.click(); URL.revokeObjectURL(url) }
  const totalPages = Math.max(1, Math.ceil((report.data?.meta.total ?? 0) / 10))
  return <section className="booking-page"><header><div><p className="kicker">REPORTING</p><h1>Laporan booking.</h1><p>Rekap perjalanan dan pemakaian armada yang dapat difilter serta diekspor.</p></div><button onClick={download}>Export Excel</button></header><section className="booking-form"><div className="form-grid"><label>Cari booking<input placeholder="Nomor, pemohon, tujuan, plat" value={filters.search} onChange={(event) => change('search', event.target.value)} /></label><label>Status booking<select value={filters.status} onChange={(event) => change('status', event.target.value)}><option value="">Semua status</option>{['PENDING_LEVEL_1','PENDING_LEVEL_2','APPROVED','REJECTED','COMPLETED'].map((item) => <option key={item}>{item}</option>)}</select></label><label>Region<select value={filters.region_id} onChange={(event) => change('region_id', event.target.value)}><option value="">Semua region</option>{lookups.data?.regions.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Kendaraan<select value={filters.vehicle_id} onChange={(event) => change('vehicle_id', event.target.value)}><option value="">Semua kendaraan</option>{lookups.data?.vehicles.map((item) => <option key={item.id} value={item.id}>{item.license_plate ?? item.name}</option>)}</select></label><label>Kategori<select value={filters.vehicle_category} onChange={(event) => change('vehicle_category', event.target.value)}><option value="">Semua kategori</option><option value="PASSENGER">Passenger</option><option value="CARGO">Cargo</option></select></label><label>Dari tanggal<input type="date" value={filters.from} onChange={(event) => change('from', event.target.value)} /></label><label>Sampai tanggal<input type="date" value={filters.to} onChange={(event) => change('to', event.target.value)} /></label></div></section><section className="table-card"><table><thead><tr><th>Booking</th><th>Pemohon</th><th>Region</th><th>Tujuan</th><th>Armada</th><th>Waktu</th><th>Status</th></tr></thead><tbody>{report.isLoading ? <tr><td colSpan={7}>Memuat laporan...</td></tr> : report.data?.data.map((row) => <tr key={row.id}><td>{row.booking_number}</td><td>{row.requester_name}</td><td>{row.region_name}</td><td>{row.destination}</td><td>{row.license_plate} · {row.driver_name}</td><td>{new Date(row.start_at).toLocaleString('id-ID')}</td><td><span className="badge">{row.status.replaceAll('_',' ')}</span></td></tr>)}</tbody></table><div className="table-toolbar"><span>{report.data?.meta.total ?? 0} hasil · halaman {page}/{totalPages}</span><div className="table-actions"><button disabled={page === 1} onClick={() => setPage(page - 1)}>Sebelumnya</button><button disabled={page >= totalPages} onClick={() => setPage(page + 1)}>Berikutnya</button></div></div></section></section>
}
